export const filesManifest = [
  { id: 'swot-analysis', chapter: '4', title: 'Análise SWOT', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/swot-analysis/4_1_modelo_swot.xlsx', filename: '4_1_modelo_swot.xlsx' },
  { id: 'interested-parties', chapter: '4', title: 'Partes interessadas', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/interested-parties/4_2_modelo_partes_interessadas.xlsx', filename: '4_2_modelo_partes_interessadas.xlsx' },
  { id: 'management-system-scope', chapter: '4', title: 'Âmbito do sistema de gestão', format: 'DOCX', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', objectKey: 'templates/management-system-scope/4_3_modelo_ambito.docx', filename: '4_3_modelo_ambito.docx' },
  { id: 'value-chain', chapter: '4', title: 'Cadeia de valor', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/value-chain/4_4_modelo_cadeia_de_valor.xlsx', filename: '4_4_modelo_cadeia_de_valor.xlsx' },
  { id: 'process-flowchart', chapter: '4', title: 'Fluxograma', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/process-flowchart/4_4_modelo_fluxograma.xlsx', filename: '4_4_modelo_fluxograma.xlsx' },
  { id: 'process-map', chapter: '4', title: 'Mapa de processos', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/process-map/4_4_modelo_mapa_de_processos.xlsx', filename: '4_4_modelo_mapa_de_processos.xlsx' },
  { id: 'integrated-policy', chapter: '5', title: 'Política integrada', format: 'DOCX', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', objectKey: 'templates/integrated-policy/5_2_modelo_politica.docx', filename: '5_2_modelo_politica.docx' },
  { id: 'responsibilities', chapter: '5', title: 'Responsabilidades', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/responsibilities/5_3_modelo_responsabilidades.xlsx', filename: '5_3_modelo_responsabilidades.xlsx' },
  { id: 'worker-consultation', chapter: '5', title: 'Consulta dos trabalhadores', format: 'PDF', contentType: 'application/pdf', objectKey: 'templates/worker-consultation/5_4_consulta_trabalhadores.pdf', filename: '5_4_consulta_trabalhadores.pdf' },
  { id: 'participation-next-steps', chapter: '5', title: 'Participação: próximos passos', format: 'DOCX', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', objectKey: 'templates/participation-next-steps/5_4_proximos_passos.docx', filename: '5_4_proximos_passos.docx' },
  { id: 'environmental-aspects', chapter: '6', title: 'Aspetos ambientais', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/environmental-aspects/6_1_modelo_aspetos_ambiental.xlsx', filename: '6_1_modelo_aspetos_ambiental.xlsx' },
  { id: 'risks-opportunities', chapter: '6', title: 'Riscos e oportunidades', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/risks-opportunities/6_1_modelo_riscos_oportunidades.xlsx', filename: '6_1_modelo_riscos_oportunidades.xlsx' },
  { id: 'objectives', chapter: '6', title: 'Objetivos', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/objectives/6_2_modelo_objetivos.xlsx', filename: '6_2_modelo_objetivos.xlsx' },
  { id: 'document-control-resources', chapter: '7', title: 'Controlo documental — recursos', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/document-control-resources/7_1_modelo_controlo_documental.xlsx', filename: '7_1_modelo_controlo_documental.xlsx' },
  { id: 'training-plan', chapter: '7', title: 'Plano de formação', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/training-plan/7_3_modelo_plano_formacao.xlsx', filename: '7_3_modelo_plano_formacao.xlsx' },
  { id: 'document-control', chapter: '7', title: 'Controlo de documentos', format: 'XLSX', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', objectKey: 'templates/document-control/7_5_modelo_controlo_documental.xlsx', filename: '7_5_modelo_controlo_documental.xlsx' },
] as const;

export type FileManifestEntry = (typeof filesManifest)[number];
